import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "inverse-primary": "#735c00",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#00dbe9",
        "error-container": "#93000a",
        "tertiary": "#00e4f2",
        "surface-container-highest": "#353534",
        "on-tertiary": "#00363a",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#002022",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "primary": "#f2ca50",
        "on-primary-container": "#554300",
        "surface-variant": "#353534",
        "secondary": "#c8c6c5",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#d0c5af",
        "tertiary-container": "#00c6d2",
        "surface-tint": "#e9c349",
        "primary-fixed": "#ffe088",
        "on-primary-fixed": "#241a00",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary": "#313030",
        "surface-bright": "#3a3939",
        "background": "#131313",
        "primary-fixed-dim": "#e9c349",
        "on-tertiary-fixed-variant": "#004f54",
        "secondary-container": "#474746",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#d4af37",
        "on-primary-fixed-variant": "#574500",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#004d53",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary-container": "#b7b5b4",
        "outline-variant": "#4d4635",
        "secondary-fixed": "#e5e2e1",
        "on-primary": "#3c2f00",
        "tertiary-fixed": "#7df4ff",
        "outline": "#99907c",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Space Grotesk", "sans-serif"],
        label: ["Inter", "sans-serif"],
        hebrew: ["Assistant", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0rem",
        lg: "0rem",
        xl: "0rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
